Making 1 dimensional arrays using numpy

In [2]:
import numpy as np

numpy.arange creates arrays with regularly incrementing values

In [ ]:
x=np.arange(1,10) #creates an array from 1 to 9. excludes the 'stop'
print(x)
print(type(x)) #<class 'numpy.ndarray'>
print(x[3]) #element at index 3 (=4)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
4


In [4]:
a=np.arange(0,5,0.5) #increment of 0.5
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


numpy.linspace creates arrays with a specified number of elements spaced equally between the specified beginning and end values including 'stop'

In [ ]:
x=np.linspace(1,10,5) #5 elements spaced equally
print(x)

[ 1.    3.25  5.5   7.75 10.  ]


np.array creates an array from a list

In [ ]:
a=np.array([1,2,3,4])
print(a)
print("\n")

b=[[1,10],[2,10]]
c=np.array(b) #creates a 2d matrix
print(c)
print("\n")

d=np.array([i for i in range(1,15,2)]) # using list comprehension
print(d)


[1 2 3 4]


[[ 1 10]
 [ 2 10]]
[ 1  3  5  7  9 11 13]
