Creating 2-D arrays

In [2]:
import numpy as np

np.eye(n,m) defines a 2-D identity matrix

In [ ]:
a=np.eye(3) #identity matrix of 3x3
print(a)
print("\n")
b=np.eye(2,4) #2 diagonal elements have value 1
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]
