Creating 2-D arrays

In [1]:
import numpy as np

np.eye(n,m) defines a 2-D identity matrix

In [ ]:
a=np.eye(3) #identity matrix of 3x3
print(a)
print("\n")
b=np.eye(2,4) #2 diagonal elements have value 1
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


np.diag creates a diagonal matrix

In [ ]:
a=np.diag([1,2,3])
print(a)
print("\n")

b=np.diag([1, 2, 3], 2) #the second argument adds a the number of new rows and columns (from the bottom left corner) with the element zero
print(b)
print("\n")

c=np.array([[1, 2], [3, 4]])
print(c)






[[1 2]
 [3 4]
 [5 8]]


numpy.zeros will create an array filled with 0 values with the specified shape

In [4]:
print(np.zeros((2,3)))
print(np.zeros((2,3,2)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


numpy.ones will create an array filled with 1 values

In [5]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]
