In [3]:
import numpy as np

.shape tell the number of rows and columns it has

In [9]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.shape)

x=np.arange(10)
print(x)
x.shape=(2,5) #x is now 2 dimensional
print(x)
print(x[1,3])

(2, 3)
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
8


numpy.reshape gives a new shape to an array without changing its data

In [10]:
a = np.arange(6).reshape((3, 2))
print(a)

[[0 1]
 [2 3]
 [4 5]]
